# Generated by Django 3.2.4 on 2024-09-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('formal', 'Formal'), ('casual', 'Casual'), ('party', 'Party')], max_length=50),
        ),
    ]
